name: "Dump GitHub Actions available commands"

on:
  workflow_dispatch:

jobs:
  dump-commands:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make clean
    - run: make sources README.md github-compgen.txt
    - uses: zwaldowski/git-commit-action@v1
    - uses: ad-m/github-push-action@master
